
name: Build, Scan and Push to ECR

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: eu-north-1
  AWS_ACCOUNT_ID: "810100780119"
  ECR_BACKEND_REPOSITORY: blogapp-backend
  ECR_FRONTEND_REPOSITORY: blogapp-frontend

jobs:
  build-scan-push:
    name: Build, Scan and Push Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::810100780119:role/GitHubActionsBlogAppECRRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tags
        id: image-tags
        run: |
          echo "backend_image=${{ steps.login-ecr.outputs.registry }}/${ECR_BACKEND_REPOSITORY}:${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          echo "frontend_image=${{ steps.login-ecr.outputs.registry }}/${ECR_FRONTEND_REPOSITORY}:${GITHUB_SHA}" >> "$GITHUB_OUTPUT"

      - name: Build backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          load: true
          push: false
          tags: |
            blogapp-backend:${{ github.sha }}

      - name: Scan backend image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: blogapp-backend:${{ github.sha }}
          format: table
          exit-code: "0"
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH

      - name: Tag backend image for ECR
        run: |
          docker tag \
            blogapp-backend:${{ github.sha }} \
            ${{ steps.image-tags.outputs.backend_image }}

      - name: Push backend image to ECR
        run: |
          docker push ${{ steps.image-tags.outputs.backend_image }}

      - name: Build frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          load: true
          push: false
          tags: |
            blogapp-frontend:${{ github.sha }}

      - name: Scan backend image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: blogapp-backend:${{ github.sha }}
          format: json
          output: trivy-backend-report.json
          exit-code: "0"
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH

      - name: Upload backend Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-backend-report
          path: trivy-backend-report.json

      - name: Tag frontend image for ECR
        run: |
          docker tag \
            blogapp-frontend:${{ github.sha }} \
            ${{ steps.image-tags.outputs.frontend_image }}

      - name: Push frontend image to ECR
        run: |
          docker push ${{ steps.image-tags.outputs.frontend_image }}